export const elIconList = [
  'el-icon-platform-eleme', 'el-icon-eleme', 'el-icon-delete-solid', 'el-icon-delete', 'el-icon-s-tools', 'el-icon-setting',
  'el-icon-user-solid', 'el-icon-user', 'el-icon-phone', 'el-icon-phone-outline', 'el-icon-more', 'el-icon-more-outline',
  'el-icon-star-on', 'el-icon-star-off', 'el-icon-s-goods', 'el-icon-goods', 'el-icon-warning', 'el-icon-warning-outline',
  'el-icon-question', 'el-icon-info', 'el-icon-remove', 'el-icon-circle-plus', 'el-icon-success', 'el-icon-error',
  'el-icon-zoom-in', 'el-icon-zoom-out', 'el-icon-remove-outline', 'el-icon-circle-plus-outline', 'el-icon-circle-check',
  'el-icon-circle-close', 'el-icon-s-help', 'el-icon-help', 'el-icon-minus', 'el-icon-plus', 'el-icon-check', 'el-icon-close',
  'el-icon-picture', 'el-icon-picture-outline', 'el-icon-picture-outline-round', 'el-icon-upload', 'el-icon-upload2', 'el-icon-download',
  'el-icon-camera-solid', 'el-icon-camera', 'el-icon-video-camera-solid', 'el-icon-video-camera', 'el-icon-message-solid', 'el-icon-bell'
]
export const omsIconList = [
  'oms-icon-pay',
  'oms-icon-transfer',
  'oms-icon-optimization',
  'oms-icon-collect',
  'oms-icon-cube',
  'oms-icon-store',
  'oms-icon-project',
  'oms-icon-automation',
  'oms-icon-afterSale',
  'oms-icon-attribute',
  'oms-icon-govern',
  'oms-icon-nodata',
  'oms-icon-addChild',
  'oms-icon-gui',
  'oms-icon-tool',
  'oms-icon-baoxian',
  'oms-icon-vip',
  'oms-icon-bao',
  'oms-icon-index',
  'oms-icon-audit',
  'oms-icon-toggle',
  'oms-icon-ad',
  'oms-icon-gift',
  'oms-icon-coupons',
  'oms-icon-lucky',
  'oms-icon-sort',
  'oms-icon-happy',
  'oms-icon-duanxin',
  'oms-icon-aikucun',
  'oms-icon-wenhao'
]
